// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivyqkprlrosapkmmwkeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2eXFrcHJscm9zYXBrbW13a2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NDE0NTksImV4cCI6MjA4ODUxNzQ1OX0.sUDOxXBvGBjh_ZoG_K4m7zO-uE-phNtHq2AylrJZVxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});